{
 "title": "Kubernetes Cluster Overview",
 "description": "Kubernetes集群资源使用统计分布",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "NameSpace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_build_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "[ Kubernetes] -  集群信息数据统计",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kubernetes version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubernetes_build_info{instance=~\".+-k8s-cp1\"}",
     "legendFormat": "{{gitVersion}}"
    }
   ]
  },
  {
   "title": "Control Plane",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubernetes_build_info{kubernetes_io_roles=\"master\"})"
    }
   ]
  },
  {
   "title": "Work node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubernetes_build_info{node_role_kubernetes_io_worker=\"worker\"})"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_info)" }
   ]
  },
  {
   "title": "Pod Count by namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$NameSpace\"})"
    }
   ]
  },
  {
   "title": "Memory Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes{node!~\".+cp.+\"})"
    }
   ]
  },
  {
   "title": "Memory requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node!~\".+cp.+\"})"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node!~\".+cp.+\"})"
    }
   ]
  },
  {
   "title": "CPU Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{node!~\".+cp.+\"})"
    }
   ]
  },
  {
   "title": "CPU requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node!~\".+cp.+\"})"
    }
   ]
  },
  {
   "title": "CPU limits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{node!~\".+cp.+\"})"
    }
   ]
  },
  {
   "title": "资源分配",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"prod-be-k8s-wn(1[0-6]|[6-9])\"})",
     "legendFormat": "内存受限"
    },
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes{node=~\"prod-be-k8s-wn(1[0-6]|[6-9])\"})",
     "legendFormat": "内存容量"
    }
   ]
  },
  {
   "title": "CPU 使用分配",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{node=\"$Node\"})by(__name__,node)",
     "legendFormat": "file descriptior"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$Node\"})by(__name__,node)",
     "legendFormat": "file descriptior"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$Node\"})by(__name__,node)",
     "legendFormat": "file descriptior"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{node=~\"$Node\"})by(__name__,node)",
     "legendFormat": "file descriptior"
    }
   ]
  },
  {
   "title": "内存使用分配",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes{node=\"$Node\"})by(__name__,node)",
     "legendFormat": "file descriptior"
    },
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$Node\"})by(__name__,node)",
     "legendFormat": "file descriptior"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$Node\"})by(__name__,node)",
     "legendFormat": "file descriptior"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"$Node\"})by(__name__,node)",
     "legendFormat": "file descriptior"
    }
   ]
  },
  {
   "title": "资源分配",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{node=~\"prod-be-k8s-wn(1[0-6]|[6-9])\"})",
     "legendFormat": "CPU受限"
    },
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{node=~\"prod-be-k8s-wn(1[0-6]|[6-9])\"})",
     "legendFormat": "CPU容量"
    }
   ]
  },
  {
   "title": "事件消息",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting_reason)by(namespace,pod,reason) == 1",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "Kubernetes workload",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info)by(namespace)",
     "legendFormat": "file descriptior"
    },
    {
     "expr": "count(kube_pod_info)by(namespace)",
     "legendFormat": "file descriptior"
    },
    {
     "expr": "count(kube_service_info)by(namespace)",
     "legendFormat": "file descriptior"
    }
   ]
  },
  {
   "title": "Pod 运行状态",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$NameSpace\"})by(phase,namespace)",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Container 运行状态",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"$NameSpace\"})by(namespace,__name__)",
     "legendFormat": "User"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"$NameSpace\"})by(namespace,__name__)",
     "legendFormat": "User"
    },
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"$NameSpace\"})by(namespace,__name__)",
     "legendFormat": "User"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=\"$NameSpace\"})by(namespace,__name__)",
     "legendFormat": "User"
    }
   ]
  }
 ]
}