---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secret
  namespace: default
spec:
  encryptedData:
    password: AgCQa/Kp5doX2IJlZ3KJ1l+znSVWOzscOt5vI1N+Fg03hrW2p3fuqwUCDqo+RjQCxvNpOWq0/I0YIWuF01eEIcTHHCbmpijZjrmDzQIQaTPJa8dmLOUh457Jgp4JFZpEvMPdw6+aIcw3ZQy42WZqZUF3q5pECbTvDyQAnksuIHJSoRxhvU+kYHyLjsON2ep94nY/Xjqo7pWVFmQDXydIvVqwWTE4oi2kzK7lHFofNw+KNozTyL62SJt8q2RF7Xubb6JbuWopzY9NqzP61G13KcJDryey0902DP52cfFL9rKjSgUqaWIKxSY2hJtN/cetBY5cZjt7G2d5FoKRFQyUJyVAm/1lgZ0QNv41FWK9DXqra0CMsDLsWdbCdM3fJV4C0qkHHm/NKqCyGxFa8Ah/qDy2CR3kxxazDjOfjhAP+hewjQv6uKHnH8A7ZRXwpzZWwylZFaxLsCa88l2wPxqIWSAQW+FhLdg6fi3sG6ArUTr7pwvj94LVMGPx8d1AVLzaSEdVsukr8OX7iPXlLYpFU7nmWu656UEwDdR3C1VYzeI4cwsQXZrkkCf0qsy+MPx0Jc0gZm67RGmkOAd7fhOCj5kfzhF+79kIX4nk0djaz8a/9GTI/AYo8jD7u7lNKeT6cKkt/vJxgEqLomV7H4tYiXPzROgGSK30H+sLeEntF8kKBQ63eSGUHNct2TgrxjX7ADU+BM9kgDM9qITsac5j2fw92FFI3BM+7BoH
    username: AgA5sLN7p7qEJUtviVi1mDPigwq0vBH+g45sFzzEGlx3fvFl+eGrxCbjE3ggXMbwzVGOAEi/zh7ygYoc408oymy/xXWpxPsOPowb3Dy33PrDjKJe//KcVT2Rp8Eaqh8/GWxbkIZQRIPx2dqhDCDGNxqtMiBUBRfqSdfmSBvS/aUv3Qk8Qr5rWWRALmHII+m3W7V4i9KMLmMHOq7ZFMVkRdv7PtNlnpdMhPOb3p4xccchZT1mRX4AHqo4ciU3Ws93Z3VWZVVjLnxWIoGKJyTrXlK0mbpzm5Gf9KrvopEbelcjxtaolgeha23czZd08YFgLNLgUi0hR7LdI3OUTVra6UGrot6SPZWvcgAHnwJNdPdsKmVmrWJLQXdYfzEjg3ENdZ2sBjXcSVEVbhhE8iCcgFiavL1AsnAvKZKeOULEKGZTDqIZs4PgQdun2kjyErweWiAqym0aVrlYlsMFwU0+0K+ju4q17xfVA6Zv3WPlsuezPYICAvoIMa/zzgAmA0DjL9udp+tjnaQHfV8TMIKC6Jw3tofKxwuKwB1m3Rzg4GF3DYNearoQhU73epOjUIXt6+Ik3CSL9EnWZE496x7cZEeZ/Kl1u4mHKd3tIOgE3qvH/mCnLh6CBz/5lwj7trB0yE0H9s2GGYdKB3PjKnxUnDGbHps+53d2bf1dpD6X4jToDOjEN3fIOTO3ZFG/s0cYfJG56OzlYg==
  template:
    metadata:
      name: demo-secret
      namespace: default
    type: Opaque
