---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-password
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCK5ryU5xIrYCzZOyEAyZfYt/PORZfj1cRZMiRW3VQDVIR1uvjH26sZdlDx5N185T6CdRza70ftVS8zgMpjfFR3xhym9X5+XNEEFx9E8MHyi/NwdlMLCWoAEwUsW9q8hyicS5zFZ/Gau/fMqxdX4g3E/nQ+dDeI3FVaCsm6uK5any+fsJE4108OjEYayb7N7mL4RnUqLdFzQkBom9559w+u9/x7TL2HdVx++a8Ct1KoDYui4zws9OOy4chc5fnurLUCrJykKjJqDpDIRdl+HeFbTuSjcYLJ4KQ3YYSltDPMiGggFBLqJEGp7T4cgKpITqDHnE5DoLX1iPQhimyyQiQRjL29seadpPBTMqHi3qUn1cxOMUDg7+lfI6aQiR1l4IW1D/mSEHmd34r1qPfGStGSmiPgx9yydJ8i/dJ/jJ81XQYwvzgeV+7zGCqTfSmQ/KjOosYxHcyUZQU8MLmWOuGfqMb4WyXSIWO4cv0jZBIRycHDjEF+lZcIwPuZ3yYlRo2PV55uCMmHvbyTtoiGF1qIqYQiwp8Yh5dY7HwphIifcY4E7F+md1JNTu7WFFiNgoSe1G3g3oyRmYEvBsUhB2dkbVl/BBQY+T2GCs0Ja8FzN1EfadTzLgK7y+wz98wrDuRWfrA6t+9xKghC4qq4JfKSPPgbuahrSrx77tT3zQ1gsy96Ae0dOsZbXOWtk/G5hhZtpJJ11nOZLT7pv0I9sqVYdXEgr+z2M96LMwY=
  template:
    metadata:
      name: grafana-admin-password
      namespace: monitoring
    type: Opaque
