---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-password
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgArhW28/SCUiGkBYpHVcL6Nf6qW6i0x4UMAfxN+4Iwr96xSQaJwrvT3PbY0YtdYkTcFH8BHJR9IlMnhhI6FQOrTTSnujsh1ZJ9AFsovSIFlM022wTmbM1S9tGWSwWMKafNXdGCYseZeXZ0Q2MEFi56DXOeBLdPcnuFj055cd3FYxGw/mJ7fmNmbwMoL218/1vJpGUjJOHUYap2pIOeBu3o12bAaqP2ubDVkcS66e9WXi9ZWoQ+cPmlahSCCguzeYQdhGJEnCKVfCt1WxZvgRjkRrZaLUHky2wV0IyK7EQPGlr7EJMEn2bww41DzSvAePJlwq3JiVhQ3kVALoutYLnfbEzypc3c2vPuhjaVl2oczCnwXoh4oFtjK1TC0229iYoBCMSUhSukKSY6JP7VQ6UOomAkCHNlbREHXPW9UOkPSjnqeuG5+5sEjDR+SwyDqLwm+nSqcFJy9mC7PVoPei4w+h2pLj4UnROB/YdipmSLIApEDn6/+Gcr5tVL54XckQed9b4wjKijb2rYNIR5859h5VZ76+aEWd4iORqKbD+1SDpQTT8kW6xqGJCwhEr83RyvkemqF4vQoUB38FOY5d7ud1dyAK+8AB4vBwp2jRsp/MES/EAjY9n55XmDxodL+/yGXVLubQolMd0T7R7Q5y8MS5UM9bxRc5RaQ95Hg0K7XLZcvnl16JJHzh/sd8a9QxtVp9xySkrdxpuKYgNOazUUV3XnUEkOhdwI9I0c=
    admin-user: AgBvHhiAz0IZF9wdtyv0rK0wwlL8RPsOYMRX9IipPFGrGMkPm/Vliy3tTqTc1PZ5v4qvOaQ1kkNEl+5hC6889zIlvQqC5HFTW25w52Amp/mWKEFZejrPXtyH/pTJosM4LZ9UyVH/8zmevhB5ytl4y+QdThpqO6RfVZdRkxEyx/ZNXmoKrcxh101J+qC++IugGHL6giNHLb7NcT8KP+9IwDwnSymrzvmAf3b1xD5i/osSyyYHCW629e8CZImUqMnkh+oRcicImBhBmo06xOhR6egUchKS6s9E/s0Zb8+OMX0SnsjVO5yR0fZZpi6YySPFDNL4RyWjvNncbkCT7KzgBjhAg871Iq8XY9vc11L96iBIlOJJVVYBOLXI72ffggRiXcLuIVD7auYc4EodcAxJbEVc3SI2kaRewwvbkUMsNvgKjRC/Lnr4T6aHwO95FmtJY0p9w/cSKvZdJWM3Qlj6B8MtldK9hII+bC464GCQZStEHBls6JVZ1wC/CdfFCuiILoEEAMsw+FAlbBFuf2UaniuamGk/MUwfRfRXxYnyv4EmZhsLyYcFbc7Xm4IDv1oH+A0qJvpQ9VDuLF3VUub9f1MqmYl/9Ece+4dWU/XsPNVTdDuMKgV0E6gEuDJs4Y7lm36w4AzvRjg0mMZ1kIlf7GvTVSXKWYbAXjT/gE4Ix38GtL7s4p70D4ukOcwJEXa0Pw1wemK5Tg==
  template:
    metadata:
      name: grafana-admin-password
      namespace: monitoring
    type: Opaque
