---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-password
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBBY1Na4GG4t13V6+m2Sh7aQdEPjyKFcnCrK2hsY0ZPoVRT19bzRKXJCsFXesRA7Fh1Hu8hvD7XElgADPtlGSGWl/vRWp7XGeqg09WtHyPhZkmZhjdpgWXwafgKeBJ/q8MUuugaDq6dxkojnlg3DxO8dfn22ttu3yP4lcxgg1nszhcC1sz4QdXW7FTlJ3LpbpryxOebkX/OZdJ73LuUXX2Gp2SYFCzTeG3Zs4PSreQ5nVUV1W4Bz0fBadL6q3EKeIrj9v7mPGSeK3OrzeQsMqsjlOIg3CfcPNhUOIu5mf4PlVSjR9BUXzWhYZMYi5UR+fQjJVRt7fR2yRwoGYeAtsSEs+87pil904tq2WoQW3+i2ZdHQW78juBErR1wuqzmaQ3pX2jZAGnuMKpLhBe8KGmMvpFVkj5QsERy+vsTueSNi8gLzUjUNQJVE93QxH9qIuo6jCyY7a99OSlJRMjlQapLXmHkpygrsaLDc7WHS3MkU9AZPo1TN4D7qeyrDNI0a3RurWeoacqkJmLebxykX5ySUE+Am8zLA6jE1MCXglJj/p0Pvp2c02wWS/HLMAB/imUm+ZQtP0gpX8NlOcWmIfVPEX/US6FNC/GW3dBvTC6M9EXrBGLlO0GcTbwqmvBeIRipMcbzE719CBxJn3u00IWemeuT4BL9jQZn4F9kq763OL8vRUBaVBrJISLWuGPNmPzS/pzLLQGmaW6vXlGzEiXdJA==
    admin-user: AgBRjJxMjZJ25gq+pAyVtY9h8STKgS6KZIaUHTZ9DSEaoRNpO+7GpurMhS+UoYUoI47O9w35CHZRFCgFAIjK6PR+WDRjG6bSlX2NJ86hxXuAHMHLmYrktTHL0YpMfZQunSCmez6oK0cvL5LViPIuDPd+tXkmyfQrrlsEDrXdettkylyP2vySOyf4ohGIpRBoThbPMBZdsiG4VmJrpbr5upoUJlm1d6apBHiMO8rsw82x/OcDkf5uN4eoDkeXLslP7WwC/4B0cMy2TBxLl/14VAnvsPcnc9pukkcV0idiUZbWgvOwdc6eLTJKB1PVzQFBvt7vNwAhvsqmGce7lRNgcn6rmx0m6VQJLcFUZfK5cYvHB5tdzqS/etqo//aqw4V5fPXc911PlRxLXV9A8YVLMcby80Yh2n82zRhA9JGw1IuBbLo9aKWhT2M7rBgoaJ/olaWdD3W3Fc9CDul+N+aSFCU9Ga4/x/eEjKmEOe9/xFi4v6ja4hIRyxrZB6R4drlKyeRFqsKYuXRXJBu40eBkn8ICxS+Qs6J7IQjajW87SsJvXQT+W9RdRG0ntoC05P594VmW8VZWiEJqoksIdq9Z+FOcVs78yVOHDbc3edYGHew7QsWYT4oeOVC15veKbd2dkmtLGJxj+meMQ3zprYzi30IDCcUvPmxSoq5RGtgNJUyRB1AwZSMXV40PC5ih15O4mNASZnQrmA==
  template:
    metadata:
      name: grafana-admin-password
      namespace: monitoring
    type: Opaque
