grafana:
  admin:
    existingSecret: grafana-admin-password
  grafana.ini:
    server:
      root_url: https://grafana.local
  envFromSecret: slack-webhook
  extraConfigmapMounts:
    - name: alerting-provisioning
      configMap: grafana-alerting-provisioning
      mountPath: /etc/grafana/provisioning/alerting
      readOnly: true