---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: minio-system
spec:
  encryptedData:
    rootPassword: AgADu/PiocwkHBDdDc3/phRg74FGmKA+gVCQKF6W/1bOMU0WbTZGqrpWWpIoeU83vP3LeBzb2S2E465NFB+/8tLvz3w8cqUUmk5AP40L1hwEjLfHwbo1KvkQoSzOsPpX9JjjjeiXn0ro0J4x7NEFcCELef50ThhmwYiJDozaD9xqyELlLfhiWnsarpcoejhUZ1Gs3/8/VNcOPwBySIp2ILcG4UEL21f5dlYKp3q0lOKq+EY8CfuFQd4A+RYHEW61gY1xlPdZxxT9ImC8YraGvI8ql+fGIHdbqbBdwyXTshy5sisVdd9sHKHBVrbtPDd8sIP+qxfadPG6EZKizmiR+0d0A9peF66Ft69dNVZVuR3WemQKrx0jL9JJy9gnNGBQsx4qQuBtftKJeTfCg3TQWrzjw1cRIo8dgKm4gWbBhu3ojcuZDWHG4aXqifM3gW99oE6MM+4t9SKgggbV8B5K9LncgN6rrPXnl2nZsCFlTHFiL1GCO6yleN5B30gQ0l2AfZZhw1sKWfuQhJTtuFAqC2wtMfJs5n/cgMqwgmQ3W+eGQGL7XrlnabiJl0dBAmarX06zJneeMQAPMtgI48jdXeUoqmLxKCEQizdP6/w633VETVqDfwVTbq30El0iFu7xL3kPCDgot00Kb0Ch4p6zEINvH3R452BKBf0GuGQMfe4z8wkE84wgC+Svo1ESeINNrVAclpJiOe4jsKPl+DNH++F3S9P2IifKT1Yo8stt+UB+HA==
    rootUser: AgCL9+h2Vgcwt2DwYcux9H6ON809REyNTuZ/rsj6NptNsCOd6cRgFq4V964vAooMI0PosMP8+ZkLaJ5M1efoOxp7UxSU8+EQ5EjCyqFb5fAx8qVTU7G0V1ubTIbQgwDx/hX0IegifxEgVWrMO2Pgtvxf/9beLrKPWlHFz4L4BjzkMgznLA7IYQCMNYGKZfWAWW+eZwF0f5mLyh6Z0C+/J4hYl02lNZV/0Zn5mj69kguhggRQcHkr6i9pDdrL6H4jmfgesyucgP1JN6nqMzdYRNkecO6xw0nJHWKTkNzpKUMvOUdqo+9SZJr96wsKk2iUHBlm44eKidJUwpTgCwq93MvyBOAwrtpl8iUlifjURTULjxVhDYlbSuKU5j7XRm6VXBy2+iE0PaxlCI7spkZSjgBd7WM4l/NOXjTfnmYiRUZfUJ18bOF4Tjw13L8jVHwCfapGpVuIKURvLSqlB0eqDXHJZo+xdMwZH+GD17eaUS01a0H2cSRTx5u7kNlboxZo+Nl5kbIMhgKCel/EO52JqRp/+Vd6OnLqtbGBvNW+gUGF6ud6oAImRyjmT+Oel4yoTm75yk/fXkYToSCrEr8K7AyQcyJ+GROobk86gDYnn7k88CIy6LwIDoBN7ILeawfBiPn3I6hqK9CFvRAI6Iocaf0c8ol/RgV4vKdWyNtM1LljPncPcjXXgSzIVuysDtAXjjNSIrGmTA==
  template:
    metadata:
      name: minio-credentials
      namespace: minio-system
    type: Opaque
