---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: minio-system
spec:
  encryptedData:
    rootPassword: AgBh8fWEkWUxofV6gU0CF1wC+B5aSKCjs8FhlpCCZeFuqn2X9zo2bGfF98rfsEIRondeZDVZcI/6uf1K649aQONN3A9uASYcK0kaEWFwW767OJmGHIj1a4NNULuFYgd8ArlFq2uJ3l1oUrBG7dgF/U5Dzib2czdzm8mNmbgwI7GO5SBMB7mey+IIfgNbJNWBBwlR+8gKL3yJWrPwxpL0g47kutBkCWorCnVwLusoVpUX86Guqnh6cjPpPecAYwopy/E1AVl9qu8vNZOz8aq+0AxCOoYhlrS3SXirCbzd7bgn1yfBd5iCL2bJRuI1/KgHZQVz/JhbqLMSTnyWbMJeakE7Y0u3MJS16Rw7KFzdVYgYDmoEzBvuLGEcHPEvggcMPbRC3whM/yEk9USqRKPQXOJoD86WWcrRncwOnb8WbNPx8i4+dHVD19v/E/KwmRSe1L1F7df5O1U+B2mRJSAgBZG1m7zO1RSriPGxsLBkY3dLM0z/VjWOnreHxO/oC7zlp1i0De/r/PKzkXjwWZYwAvP3FTteapr1hLSy6Rl4wO1YzavbYDf06rjMxJIeoW/8vUqYVZmGed5s97Aps5JsANGxXVZz7rL18eh+F7PACxSSwYZCe3CRtfYT+c8OVy8IvaS9UXbFNt8rhfRpF1EcWr+QIAqPLY1GcWXh6fOvFkdEB1r78kaDbBpXEXvBTrv41dqTp4ZHyNbEipIja79N+8VYhwF3WVN89slR+f2NoDjn9w==
    rootUser: AgA+Ij3CDNH4uJSh3/Oxvq9yfO+XgqbjpfG/1AAfwQ+Ijyf4PAInxMD+sUoEzHsbFvSeaBZPKvMc8ebSbefd+XOxRqs5/HsokW6ghW97HujqjMGMa/3KLmJ3rsSlQgJ4o1Cg5NmpTcub12dnk3yYiDhTNdiktykkYCo5h862x1W79xVuMhKntO3IRBp8MXHSduHelFzDWTbfVHOwHV9l+q1FKhTRMh5kFCug4bN3ADwVydo05k4kox7qnOqVzXkjlVzxBEzIbOeaWD0433V4BeJkR8HEMdaKBI5G0me1npkh/vzCOAXdKRxLLdY3IGfFG3qBHDiKHZ3gY7RZCfm0l25TnmjyTTMPF3f/1yuKrfIvQt9mmV4Q/etDQnTz1I23SgjJQmAZYba8fXq7wG6i//D2wIqZzq/0TAXSMNzMdMhhscri54HfP4n+hEQr4BIeVygajAVzMByMdtenI+cBUTSisedAAWZzYmiUxc7Y08eyNCqp1XH6p63xIP2rvcoaTrxPJByq6Prgj7PAIF3sRRMyT2VL5wRx8PtbsDOKe2Ji5WBJMUFoHaTqsN707/uiLRNVbsE0G6tJSbKG+wNaTEvq6VDjT2Mfnl9SvoVBazd0t6Yk8flfYJEmoz4iR024VByhDw9nKN2q1WfGyuavU9MKaBNS0XVJ4KbBhAX4cVOalOm+Xj6gcec0ZgBs6DYdhdaDadBDfw==
  template:
    metadata:
      name: minio-credentials
      namespace: minio-system
    type: Opaque
