apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledge-graph-api
  namespace: knowledge
spec:
  replicas: 1
  selector:
    matchLabels: {app: knowledge-graph-api}
  template:
    metadata:
      labels: {app: knowledge-graph-api}
    spec:
      containers:
        - name: app
          image: ghcr.io/sadqwes/knowledge-graph-api:100ed3a
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:postgresql://knowledge-postgres-postgresql.knowledge.svc.cluster.local:5432/kg
            - name: DB_USER
              value: kg
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: kg-postgres-creds
                  key: password
          readinessProbe:
            httpGet: {path: /actuator/health, port: 8080}
          livenessProbe:
            httpGet: {path: /actuator/health, port: 8080}
          resources:
            requests: {cpu: 100m, memory: 256Mi}
            limits: {memory: 512Mi}
