---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kg-postgres-creds
  namespace: knowledge
spec:
  encryptedData:
    password: AgBMWW5pGhCbBfSK4nEPEfJfSsxqTX3Z/fYK/hjXMxINyAhba6Fp3FsFvCjfbh7PB5eaYaxvNfsufLHeRKJqfXUpiTWu4kQf/a4OqpE/51wjGZn6Q0No0gQr4mNi4o8dSKBh886tXS9RcSIGh983JJbeIN96yJAHWQV+JpI1PjJU1xfGfqf27MDW1UyX8dfWLJu2daRSSqDpjrbnuw6YOIz7WvWVDGV/jsBUzIxMkNv503MPGEJW0CDx+N1SOtWkxzExr10c/GKZO9vjoqmzOxog1Ay8+JsBAzo3jw3ligjX4E6Azk8EzjYUsNa1CtOvItEVeixn78na3QTdHsF/+OFlEZoJ/ubzQCuZ17grnx498GvEsjGpGbD2pgSV8qQ+LfQGOD5KDiJP2TnJVSVoD0QPH8cwBQ3GbU95y2rVFtEKJY+AYQpmtFM8KSisQSf5GPVXhgG2saRmWK0M0jmBu5aMkA6uJ7IinX/ADJCWLxXDK1NZx547BkBfnRCCzUxtCoOM2+LjQvAmooiojy+XfwITJzxDQY2VCzceMAjAEdyCh1KeFQTLVEtBvNEi09vmdAzNrnuORjngIodCpStsfTxJkCxPnpcBKelqwqpj+JKgh4RHxRT/rSzjzXdurX0GdmLxrwLDpCyEMiGWrvQyLqWN+OIUulD50JA4/xGKmg7jLnCwlDqnrrkRoVIgM64TedeX9DSiuYiorsiYRKNYB7dkCTQWZKahqe6N1AjlLy9/HA==
    postgres-password: AgCdv8UoZqmAf8v4OYuZQ3DlyGSi4NVCEoqfI3i+qwqGksv9kAF0zl00DYIVGu7bQoR2dTOjikPAtBO5wsWsQhSROFiokKOn9etXBIWFbR1p0ZQuByUyRfH1wNkdJaZRRfl5AQqHCe59k7IYUTjXOKjeLq/sPp/X6UbuT4mppfiYdV1oedILLep6sQHKKSTx9BjE5VetpySS4vTuB1iVlb+cU7ZPMsH2Z+EG4KrTVOfBH+H1tiCUGs+BWqPBlO5slI+C08tIkVipFkTdj0lwBKEsKn3L7GoMCG0+sAjIOvA2DIRxJ3pEYAYkh5fgX/2r/5p4urySH3hRW1d1TZPfwbBGqd+wPr37vZSmo4AEWTe2RxshICkmObexfZYhfXT+ZmFn4yVcvVa7rL7g8Y/c1tQ41I+dgmzhbxGiloNpJmYjTUaa3wyaJPSPzPXQER1+uZB16ZIXQtiK2W5hZoG1r5I2QTRmrg1bSEL3XekoacH3BHHqTlLMrB3NfvK4TfMn/lP3MXAsOefiLz8bSf5xG7QUqj60k9RprzX/NJLREalzLjL941Nc7Ur4bQ/MozICutALDhL/v0ZvzVucQ6XGZaY/kZHszVXSJb+b0pk3lZXj6tKVcQlsfoGB+LUaP/5Wdly0L+o78UK2Yu+ZYqMXIpchEf1rmQYBA5qZyDoTuC26a2i29fuzC0GJ0o1ca2+rAWFtcrkl5zFo14bQXGVSS37UPR2cJQQAOcmahxzjFdx5wg==
  template:
    metadata:
      name: kg-postgres-creds
      namespace: knowledge
    type: Opaque
