---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: knowledge-postgres-creds
  namespace: knowledge
spec:
  encryptedData:
    password: AgBGXOz1G79aTNC1I78pSQTMXMPF0LmK90kste76F6VO8mJhBmAGDTaCdfpy5bgLXOkymcDxUn0wnrlTtILNscJKpHO23VuE17qtbbDRTGCNFzJVPkGD510ZBhARgZwEevfDZGy5n9t/XA5dAn9QoK/zc4oDXClKzsoyLL9BOD5AXhOxRDZ6B0lYL1CiHmxtt8nQ4FEjTvLbDrhgqMzrDV1XbQdEZcEcvNw9XTwy8nua4yJABXDUWJzdouEjUTAB0CmoXhpoKJw2ElJdhuAEfnYfpLwmcdc4mW8bBS2cFP7Ug4DFW+JjHOfsJg88Pulw8zRuBeg/PQTu8krDBSjofRDc4hNXLmXgudB20kNglHetfuaE76gOHPghes/FqBkFzcO9qxRtNhk90WXAl16mqf0rrCikGAd28embf1PnpFrYJZHWBBDH78tQf6c5P+/nIXodv1wDRPzSgbhJiBd4nHOal0YzgRj9s5QK9inqqNp9LW1rckwKKP2NxiA57+YqsO5lWf6NCPI62aOkCLH4wN4hYBSFXc+DzMppv7+dxa0J5OlcDx/1BhK3AkQVbnLvRMsvZW8Ezz+i6d6s+3S7mtvqLYqzq2U3eNTLP7hvGyqIC+S9q9EMRKfluCV98WW36LJexOemrnY+48Pu5rXi0JEGV44jVLl8P3I5K2nfaE1B+WzZ6sQO3Yxoi9b7fUCg3V1a2hi+lweB5ETxHilnn5EJL6W+ny2cPB9TqLq7cscGVA==
    postgres-password: AgANuQBumgUxoFyvUVHRepyJ8NlUwpPPRdR9PgDX07AXnD6DTFbFAzyhnQQBwNaTLqZaEq0hYVk7+AqRjZlpf6L5QVNAvwGkxWsfFewIZ6UFyFBMIVnA2v5BHZBiFeUg5Tci5fMpCBASb8RtGKi8j1v0guquy1o+hs0+1GenQH5hKbvGHR61pyNH2g4zORtg1DQ5Lrcx1qm0jt4b560dWpOtFN+QDW7caslyEtmbf8rRL4GjxlOyhHT/6yWycA8Z/kHYabX80oZ/FY5FfhFx3GXncgQcS9mU+e7ZbFP0r/7RWwe6ih7o4495y0uUA38W91bLz3nuivYEyDBi2B3qYvJhv3oTDzG7LF5sra3jqoaDQ4JGxOX5SGDI416zMVs6Rjm5QGaNOqtUKUhXZN4110G3GMqXRcLYhNbHJt2nsymgy4Bpg74Pc/KxCzwOUWVXGaQR54SsWloejGuvpf2JNGdu1Kd10NThMkdtlFVIOsll5QnH+RMwKO0yq3Oug778P4i5G8RfmPuggiyTwuzxLqqPfoRFXU9L3bzArbfpvpXkXLQiEH+cXjx69EzzUmt3aj9tYFB0l2jQEjdDbuh4Bsw+M6FN/6qgOuf5OEQHwcho6nIQ2c7ni1dXhlmhlouTW6HjhqYdt5ju0xJTrOG1FcyO4XRmTBpwJPg5NmiXWJIOoQcjLRqlK9gNvS3dWUBqGBSw2slwuEowU9PpjfnvkFW36dY2bZ06DwL8HYcdaz58zw==
  template:
    metadata:
      name: knowledge-postgres-creds
      namespace: knowledge
    type: Opaque
