---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: questlog-postgres-creds
  namespace: questlog
spec:
  encryptedData:
    password: AgB05vKJGA8eHiHhFN1uOaWFoN6kmN2Geka54DumD7mmhRFDYlwwBn7OUXg7cxN91hDoi9KphgHdJNb5DnmkyDf+WwR9wVJ5OzFl7w8Ak8YNF/aZztACE8Zk/FeYGZrp/ISq4o8tm8PI6vlDtNdCn3R0+MzxPY1PgBa6UCgEutg0Dm2WLG0PRWXzXnvfts98LFHl8l12y2eVfIXwLOtodZ/NWkUFYml6n+XY+/REexh3y7lX3bzKnQeSa2DRWysuHrB9jVifE+qOOmjLgjEOuvXoa7MfCgXHXRT9LF9v9R7eY+dPfiBgGh1shgX7RPNUIPwRAe2nJM80aXxNM9pR6ZkKMq4phc1XOA0I5ArpjPLWQ2mNW1Qm1waa2P2SRw4vNrmy9NIPky1m1fV2y+NsSKUK1XAJR0r4nWcYgzOEryjKb99jrFdbpFBq9L2owNP6Tn23DpKVIUc+3jpZfj/agopcwdMeSNVNd4twKTAyVMf5Oah5ciVAZfbqP3iAuSnVJ8mLI4mPITAqFHbCegCY3FqtMbtwc0zz2HE593uxEYK/zbSyAlWsy9rC2nnkw3zC+rwm/o9WSUL04VO/WgN/d5XK0lopC3uYaSUuD3xw60daS6u0uKrcY9Lz5PmN0PlrXDU3r8SOTjOOkYFSg30VNbgAnTLrZDbwodkl16gksMt3DcgUmRBCSYBn8lFZRpeVrHsFh7aauE7au+w2egd0qwX2/QskCWUhHXcIja9q3Q6zuw==
    postgres-password: AgBQ5CEpTWhE80LpWlnJJzKdSFxVLQkdZXQj/wtXElYoid36HKjKJPP/aE6KYd5FzhG3dBUiovhKcmiDj6sWbR2PcJy502Ttjq4+WAyhbD5HlmBgQJXn+87qk0bx8zH7hj3eGrpQx9Q2qcJLKRDsHnq6s6FQMbViQrmM9Vd9FzbOhb03fMlvR8jWDRYymWiZFBBfVYLuvvYbsbFfohHv+Ysqtv2eSTxCFI+J92OKIiW9yua8MQ+xnKpsodUhGnlBs1A2NaTq/hUXRua+AxVWOBxY/CAkmiJiBNdrnCtV1k8SbptgA9iAO6AEEAUMT9q4LLf3komQVF3hb9kOHvcywxNdcswJcYdL8Mo7ztBGZttwYN0JwKVmNEPb26Wye5jY2X1z1D068Z9xY1X8IepycPuzi9U1ZnVK4YCFc9RqpFkMYdueU7nLdhluzfuCY4gzqrJO1nqXsva3zrPZXCKrPTSb8bh/FMdnUOrEtg55TF+scQngLkoHRLG2mb0ex2HmB3zK5NfvGh5gGEqnEx+XPwtNoZa41wNFpy+dd3D/tw5c0iQSN3wYw4F4Vgb7SCXrN0U1GDXphCBEgR+d07DK61neQhG5BFVTuEodGsIFzcDKwmxp6ybtnaZOnf2dYCkFYnDTkv/530n7OJYkqIU0Wd7hqupuWqGXC8LRu6GAqoBTOP5v9KzZEQnbUzNTYqEAZHWlSQ4nRuKYxQlJD2e92JJGmU/QO1ZiELfWpKDM6kNagQ==
  template:
    metadata:
      name: questlog-postgres-creds
      namespace: questlog
