---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: questlog-basic-auth
  namespace: questlog
spec:
  encryptedData:
    auth: AgAy7zb7pYybXmBj1LsEVKzBfkViLIcLjP5dBF2v8jhBJVO42srHM11rT+UzjxHwV7P8VR44BuCvLjuvjgaa5yS7MSU2dVX5ubQG0rTj9F6WPtq9fOMgVSfDqTKn6k671zrtPD0UnLp/yNPD/8ddq6HrgsHW8YSv6FsEY3CNJJx4513RaRg2pmqihqbzRk1ZFz6HQ+SFuTX/yRf+CLIRk7/OjAmss3F12hAeoBN0+AtBcV8sOz8Cnb6Nx6n+TQYdfANqAEKtThMje6KKZsdl5OewI2ciUcVhtz03C3htQcATDw3mQ+xBZQ3ck7KYo0SyMHRWmW+dA8bKUc6F1daxNhEfZUxigDGGxQUL7UuPGNWW+Dh3pF2MHpP9POmmch/3Jd+opkcXjUygvvbim8YUVvlpUBqIqwwg0y9ojDw/beWIdnlQDCtpzzauVFqyxvj3Cz+O7c1KFZvGS1U0Yoc4uCQ1TfZTdoqxerY1qIWQJ17VxYLnmF5v2Q3cEf6rKu5eoQdL5iWH99pDm2903xcAt8up4R7jZVZ6qZQU5CUBvrWcaOEa/1rmD2SQ+00CEnEQXn8aOdN3M9IOHFAwHzxJ8+FQhBqgoaMoEziNzWJmAJBHD9b8lNqeK81B5Yn9BL3U3i3M9ur3m+QIKuJlYUAqtXtjVFzOq9mEC3Iwh84BwODFvYXFhqV40HknfBvIZUqU4avZQVnyqALpWuaT+jkOTLmUoqBxylbB1pqx/xD3y4HnG5SnT3E7VRLdEiq9o9s3/plDhEWug6TaxoX3mSCVXffHjhCJcyoC
  template:
    metadata:
      name: questlog-basic-auth
      namespace: questlog
