# Generated by Terraform — do not edit manually
[control_plane]
%{for n in nodes~}
%{if n.role == "control-plane"}
${n.name} ansible_host=${n.ip}
%{endif~}
%{endfor~}

[workers]
%{for n in nodes~}
%{if n.role == "worker"}
${n.name} ansible_host=${n.ip}
%{endif~}
%{endfor~}

[k8s_cluster:children]
control_plane
workers

[k8s_cluster:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=${ssh_private_key}
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null