apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: "5.4.0"
    helm:
      releaseName: minio
      values: |
        mode: standalone
        existingSecret: minio-credentials
        image:
          repository: quay.io/minio/minio
          tag: RELEASE.2023-09-16T01-01-47Z
        persistence:
          enabled: true
          storageClass: longhorn
          size: 5Gi
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
