---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: task-api-postgres
  namespace: default
spec:
  encryptedData:
    password: AgAzzSRxMc0R6C03tp+DeeU/0zxbOYXx8bjf9os+tff+qJv4bFp6MUcIaFVxCMRswPzMDW/y66h7cCIhcLr4ss1Zpf2XIOqDxWnx7W/9iRqfogiVhyJiVB+gNyBFRzTH7RAg7YTDAPmlJ2fK8Qz5JntQPzmIdcVlWqmAlqXcvkqnXtLzO7icwBuaUHUEFnblexGPMUotkqQH8ExdMm4hVwxxiNGMQBnX+TxApGPnD4L8N/r1X6CkblnFLNG4jMHM/IDHtZwpkPR0f6erF4diU1aQJ0KHhEpsn9oiIs29YvTcPY/43LUmh2hpmcdKCd+Zt4Rhl/jzROWl300Mv7Z99JSuNuNnECnSfmnvdlR0rPPln8E+Y5uAs6y4sBP7vnRLVa53/RFlYwtVbhvcK7aE5eZhng5xpYJoSn4v7YG9F546JUW4MV4vmu00cLJYqf8YgEfAba4X6/3qBIJaYdCgPqMrRExU+/Qn/kt/7rkjpgS0+WlOc4hWnhqvdt2V58CjcxZ5MW8X0cgTUnQlquZHKwIudLTw1G2hW9VIdrBivhEpXslaKr+X9te5OPx0GZ225apZaHp+t/jLpZ3wJLFb8kq6hjk3I2EUSDqLB6tPeT8rM/CIqo0IN2jJ+B7cddRSD9ENNv9suhjIReXGOAvg5dfgEkSfELJEbTr6r540ecM3i6bVytrSMvkk/754vsjM7KquU03qXqBsL67EzsitT81YFY+5AVyT
    postgres-password: AgCWSXvdKCZ9W7v7Wh7iJz9rbEGS9YW/DTAmZbrLpMsyL4jzix5+USH5Qzm2BDfmZl6qWB7KM/8s7o0nd1gO77cOY4L5LUhsltIhBa/SCPmXndQ7J2w2dGmT2NFYIkhOOu4tQvPV99O8nF7fCJubo3RM9JqtIzOYLYvx8GbOsDzkxC6+yckStjHnrfVfhu35RuoAt4zA7sPkLbHmEm7XKF5KXEm+59X3xd/r1SlMnn0JVmEQzDqV/CP+xZVQ287B5FrYpzwJJ4r1KSYMSTgnhgivjXYllgDkDheedH4Y3Ljr/9wr3IJ51nT+dfq0VNceXtJLe4Z1GfMtNYTzhav7AJ3hX+Ud00wXl1mUl7nE3504QsLPR6+TdBPWZKqYmyLsZ3ESt8Av0UF6frpBhojPhaisdp1109S0m8ZwCRfmdvw8rLY2Lrb/ijk/yGsSCzKe8i05fLVHEnqGTOC+KdR0NLgn3GpIdB07R/q2DvjzOMyYMOMZ3+3TnOdsxkbPErvloSdkLzI/rzRCicl3Rihwssvn5DK/4Uy8SaU/piJ1XxppIinNzFhrDDXljWslZOVqR6Ymk5FzTTE1/6NxWxblDGhxWHrLK+CgxTC2mkk01fmlNypfyXNmKDFpH6CaVJjuxisg3+827u4/l2LjCQLBfPDjI0r4lJ6aAO5WJJ4OO03+FoaCE0EGDAqnmya5zo2uh9YyIeEm92QQQ75HLYUoD6lbNeScyyvK
  template:
    metadata:
      name: task-api-postgres
      namespace: default
    type: Opaque
