---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: task-api-postgres
  namespace: default
spec:
  encryptedData:
    password: AgBja3qRhfB3mfCEHt3decPs+OfY4GZdTTx8z/3UKEWx9RkdLZCJeinQ9sZKtZuouAS8ZT2OHjsVRVyKuTfNqxjZyaWQdrm61qZwjEHDm+bALjePGUrAIYA5HO81I/sdx7JlYS6z7B4Bh+aFoc5Czff/Fbt6G3eglQ+pkzD1D6ypfchhTu1/rQGez12IXftBt6CFh47jbww/AEiSOOhThlAbE7y1Ibtoa7ZtjkcYJ/jrujntBIy28v4OBUgp4n5+JbqrGQhlZfgaYjzUjBtOb4uj5+BmFFEHSIe61roRjy/e5N8cZ/OwUSX9+P2QExhmgERhBL4ksn64/hb1Z+Hstn30MfmW/UHzU1i5cPXq/FnTWi1xZYew6ZoCyQ5BF7zpFS4tNZA1NCZxWK2eIZf3u7RzqleuNI8bMC7yV8TP8NDbL0QK2y5wrmAQ402Ta49ycV3UfovASqNahNYZLUMRAmq8R6mjfiyxCUixgpV4hAYDMFX8l9Xm1mN5T9Nq8rBzm/ckdz/ZkK0xmuVoIKFsagPWTPnbvlHMjRvS4OVY1j6VgFGdUksa47Q7NnspZpsW7tXdU39GfjhkPq7yxB7Z/yofP0RZq4ir5PeU3H9zuqZPFNJORSB8BGXWKbklE5SL3Q9U2EO/WrpsF9NrJY72d27kB/dW6Lr2WQY1K/iXh7KdxS+EDyyN3rCViL75H4KLk+1qSa2atddIa/hJ/gcjYgxh2B6oJVU9
    postgres-password: AgBONPsUFGmC4AMt4+33WcjHPKDPz4gFGZP85g0HDaYzMCnbnKBorRI0ESs6C+3920OuhtV8r4/vAx1gRfI0pNBQ2ro0rKSemIqtrXgrMUPWy7uYGKa5wRdhS664zW+ZUkiWLo6jMFWAHXhaf6zEhiCPx00no1Zs0MS1jb2EvGQcyrOSbvHvB+nh34AbDhTpO2Qn5z55SeKrtu7qsYsktG5gjjjZdcS7Hhw00bugMWr3oykbdhqhHd+YyslQgfgeSY1Z0DydXtlxJY/DRz4rGJNZnG36IASp3M4ha7KSj1+FTiaq8nm2rE8As0vixgeVhPw8w08JqUBeU0Wi7VErEEER4foKSv4Lg+/ESh+yQbMs+8z+wZAOgs57LNrihFHDhx2YEfCpxFRQsev74U3kWxXAFrc9xXDu6cTDzHGsHC9uy19hZbLAnQ568kahijI0JELzKea9vBlUQFlLjHvbYgQth2YeKm1ZpXApk448/+QrnCCAaysd1KJZIYuaBxArWfRy/IZZ2zQzsLOh1b0xQdaMi5Hp7+WMxbcTIG48YW+9pRoUQSrZfR25BdbKSy6YRt03kejIOTkO8Ul1WLEY127yEnDPH88B7vlznJQvJxOk1YWeg5xC6qlTGUkwXuor9VbCS8c4WwCRCLtFd32esB727HvnrVJGHRP7bPrRmLWG4c/Z/jOD6/ECwC1qjisG1bVbSaHbto34xA4x7Hjvhzlc7j4xqECT
  template:
    metadata:
      name: task-api-postgres
      namespace: default
    type: Opaque
