---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: task-api-postgres
  namespace: default
spec:
  encryptedData:
    postgres-password: AgCEY0tugGa6rZktPMGEu4Vc7LXB+IF1ovaZYLfQ7EpnJOlVz1805mlKtiwTzkXq/JyPd/aAhsijw4aU/M98tEnRFXzIUK+o9Y2sxafE5DRRMu+11NpMEyrzXH4jNKujx6nVTchSI6nk+eODcwlkie+d0c59Osf8CiNBMmANWs96RzOB6k7sLrxDXpFccwAWKenzg4UazSjer3laCLEvWU0SpHb7isbkNlTTi7obKG6R3if2vIHUiROvWA4PArv3uNZwiPNMS5GaT2ZNX/9wcPYq+WTBY2gWtGznPaCiIMPGMDGnvC0BwIX46HuylrIB1wisUWlyubTUYuvDmzZhPQVpgwirRarHgxe8JoxX6KHzjUR1VCFuZyK9zSCDou83np43Q9mhdBGOksZlJk2aT2cucaDG20nclL+A3aPCiStRN+HeaprkHPpYJntxTH7XXW9HwHEmLH8JqI+1Mi7F+bRcXSHikbdMTnuBJ4xIU/8kOUXodm9FPGn66B4iWvRUTcQ1lBOhwUikE7m1Hj9/8Kvxt6YWsYpfh8BXSjaEB5n+L6tn87Tv8yx0kyE1GTJhmcSNa910MEseItBtBnkTPGgXOQ1b095QhY0J1p7+bODB1C3kCieupWSWgu9rbYZXM+a3tRY++GvFoGJwFD7eCZvx7UMIEK1trIQS6lvcGKyceDe6u3szpddtg5tZa/B02ooAPFxgjsxQLXdbAOP1Z91pAla6x9Yq
  template:
    metadata:
      name: task-api-postgres
      namespace: default
    type: Opaque
