---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgB26Jz09AD7E8ALnFGydapGlzhBWGm1NGADUP4ExeSVhPBQbK5GBHRiIaJ6q1nPiOP4shn70JEGd77A8D+gnBsa13PqhUK5LPTogUg9GIDmoWoAAm9UxRY7zpi8I546pbMPefigm5h1Hw+OZoU+hv1o1jOupfzOr0asLpkiOrZAsTKoNFnEMPkPO1ND3cVLSEi3fqJQQqY/JbUJDkL/g8IQXO/A8V+YCQtAggpgFjxFubIDLlI5xE8ylz6FCKUkRfgcOZQjr9NXl+2horDnEjihIFKHNs9+qJ7Bnmco1jXtpNqAAlqND7whlq5MfFNjf9tW8jljlbG0dPNYvBAViiqq3f7zgtQkd27g837aSSL9uaMXqzUup7V9yT/50BFHuFNfPMWbwV2eKs1oiI8KPFA6ispPqUv8FFZqMH7sZASMJH8Hqz7RoEazFVsbWg7y0MuIQi1F7OyXeYi1g96pFTIHJYk79ygxAU3A5RoCzVo8c0I3lwNLE5MP457VQnuVjT5dCDKj6y4phQQFidf6Y+w1AFTpNfMpIhAdudbrwRwoEbLJ8jeqFe+4uGRryF1umI1puuRBf4xvp9ukXbDgs9cuBApndjmAuTwcar5H39dY88/g4zR1S72rgRLmh58P1sPX7GTkALECh/Mq2wvKZ268HFI3ajxRbz65tBysE4CR0clwov7URWdpeyBGBnUgiLk4EKAWN/Yp4WOLq+OylhHCNonuFjnWu6GEr61cb3x2bEBHuBHcClrXg9q89VhWCUTz3J564uLhtN4lznMcYvGF0BI/UaRMlBXYDUKAdiCpMQTvijvVwxoUIw==
  template:
    metadata:
      name: velero-credentials
      namespace: velero
    type: Opaque
