---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCbq9A0QL7ubD3mD6L+BCsJULczY454ndqlRVtDTg/n5wMmG6BKWhEK4iHDMOwSDgEyeIIgZuYCrZpdNcYn1ZPtdYW8jaCnIKZmhaMQQzZi2PATercIX/OOBx4+XKj04DQeO2Em1dsJBxzMmoW0fxK0jBBU3Y4R8OK2WJGk8mWUxNXuguB6jZH6jo7A8TBXFQIS7sJ6QwPut++Sfti5BcOk/DTdy5IotBlPbLnC8048PvJBPE0cHWX8uo0ynw4up/94X3/p0b5KouFNbhNVKiUgAWlKteQpaiKQ3qIlnHTwKszEXDGf+WbtmUlmdoD+o1PLGg7SsmJiW3Qj705vV03Lzrm4put9OkhoB9OQWXPpG5Ty5cN8bYn92RdvoYmiJBGI4kip+WpnVi1EFwlBeoYsoCOsAe3vG20XYbnIYT7EYtGxqLJ9dVOFP+PDwNhySvn2QKGoz9sZjOyXwWEvGwItpmHTXg2GmajrV1TC28lgsZvqdXUfwQHl4jwCMo5HlZ8VmjvrYlwlQ/kyiDEKd96wl41PYbu3/L+jU/FCspZobfGcLWzojgZK09AaPDE8Lr2gJTfiRBZ2oT6cYva6p2H0XR+cguyq2v9M2kdwd1Ak1pW9o62PziqD64KLOmIb+wF9gu/kkasIM9EcTCLd2dNe6aNVQNGOkcjWATmWsbP1Sb8WxGEVskYvui72Xb5GMLLq5paPWzjKFVry2osGQGkB8Bs0tYTZRJoMhG9Es7gLXIUKtyTxiIa7JGqnGRGGzY1BKaCJqWwVMx6k4jehd8SKve21B2Uc3+o+gj/coSJBz29cS5sGGlYyWg==
  template:
    metadata:
      name: velero-credentials
      namespace: velero
    type: Opaque
