---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgA0dc/DDbM9VzQ6bCfG3pCKZq3pMS2gF5IGn+hcaA7owg1JFqSZTmJ6TQa5xhmpbBLCEz/N1oGZEkCHUNH/ZqsZTIWvm6OZSBjYCZq+LpU732/IzGPsBq/epe9VFuKQ/VtinT/nc5dSYRAJTdehOkksunSNwxTQOHREVxduD2KtYDkjBRI9HAHDOp3Iqaw5lW6ol1QowvP7DZ3YPoEk2fA2OZgUzhhiQCpBLZzyCRJ4Y51hOUpVS2geiMpcqnfusbPN14ZoY396bBxkYr7O7qOmSxwBaKBZjNMoydWyrF/fwgHVs4CAiMqhfl9NVl1eKY8FNAZ3sAqBrxRPeueq5u9m6cnJ7pUmVtBwBVTkcnJEa1j17iSAyKbFPB2Ns0FzV24YWKQTtnm+vVdGS/iXZeQenZq9+JflgHJImg9JpT7kcaXXmcG7KVGwFcSuYBEZrlaaVrFxcyfy0ana8LeE53LMOBndzTJzbEsug9qij5Q3g3CEB13OEEdXdPkTZU20mKAoNyazop0TPMj6STiNSgwh9ASmFlPIIxMvdnaXKUAxtie2Qp19O5LgD/TkWmlGNzh1eT4JG+Bt5mxgp8YIy1RVFF20xm3w2iWdtDp7Nyg1UJ0q7Q+Fh/rXNqHjViSIZi7HYYHXqogh+slVBhLdPv6lK0ZMl0PwFEr1ZNqtv9HUvuU7GAMwS/jH10kM4V15LzsamUJ4IqsZ7xX6Sxz4a3jNgDaLmXkoRPeGnjK55bWmCJE+4Gycw00s0weMWuUw0NliVeUBmkA1FvgGSwAFb90ez20Tz+Q3pM0=
  template:
    metadata:
      name: velero-credentials
      namespace: velero
    type: Opaque
